// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDjb_-kWSXaVAE0bNhagzdX7aqhKYnma8',
    appId: '1:289810144217:web:1ed3af70640504d7de17c8',
    messagingSenderId: '289810144217',
    projectId: 'cpsc-5250-db',
    authDomain: 'cpsc-5250-db.firebaseapp.com',
    storageBucket: 'cpsc-5250-db.firebasestorage.app',
    measurementId: 'G-K31EMXT7E4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTJpkDoN6pupmznVOicVdXZC1FbVqCCpA',
    appId: '1:289810144217:android:4ab40ce5e0afa523de17c8',
    messagingSenderId: '289810144217',
    projectId: 'cpsc-5250-db',
    storageBucket: 'cpsc-5250-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMLpLyR793__YpsROD6MBtP4zBLEhnBZQ',
    appId: '1:289810144217:ios:aa347ba6f862eafade17c8',
    messagingSenderId: '289810144217',
    projectId: 'cpsc-5250-db',
    storageBucket: 'cpsc-5250-db.firebasestorage.app',
    iosBundleId: 'com.example.eduardosousasilva.eduardoPersonalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMLpLyR793__YpsROD6MBtP4zBLEhnBZQ',
    appId: '1:289810144217:ios:aa347ba6f862eafade17c8',
    messagingSenderId: '289810144217',
    projectId: 'cpsc-5250-db',
    storageBucket: 'cpsc-5250-db.firebasestorage.app',
    iosBundleId: 'com.example.eduardosousasilva.eduardoPersonalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDjb_-kWSXaVAE0bNhagzdX7aqhKYnma8',
    appId: '1:289810144217:web:54d5277e0e37ae52de17c8',
    messagingSenderId: '289810144217',
    projectId: 'cpsc-5250-db',
    authDomain: 'cpsc-5250-db.firebaseapp.com',
    storageBucket: 'cpsc-5250-db.firebasestorage.app',
    measurementId: 'G-2LD82S1V6Q',
  );
}
